// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;
namespace AssemblyCSharp
{
		public class Consumer{
			public string url;
			public Action<String> OnComplete;
			
			public Consumer(string _url, Action<String>onComplete){
				this.url = _url;
				this.OnComplete=onComplete;
			}
			
			public IEnumerator Start() {
				WWW www = new WWW(url);
				yield return www;
				OnComplete (www.text);
			}
	}
}

