// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
namespace AssemblyCSharp
{
		public class Trip
		{
				public List<TripBooking> Bookings;
				public Trip ()
				{
					Bookings = new List<TripBooking> ();
				}
		public List<TripLeg> AirLegs{
			get{
				return getLegMode("Air");
			}
		}

		public List<TripLeg> HotelLegs{
			get{
				return getLegMode("Hotel");
			}
		}

		public List<TripLeg> CarLegs{
			get{
				return getLegMode("Car");
			}
		}

			public List<TripLeg> getLegMode(String mode){
			return this.Bookings
				.SelectMany (booking => booking.Segments)
					.Where(seg=>seg.Mode==mode)
					.SelectMany (seg => seg.Legs)
					.ToList ();
			}
		}
}

