// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
namespace AssemblyCSharp
{
		public class TripLeg
		{
				
		public DateTime Start;
		public DateTime End;
		public Vector2 StartLocation;
		public Vector2 EndLocation;
		public String Name;
				public TripLeg ()
				{
					
				}
		}
}

