// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;


public class Utils
{
		public Utils ()
		{

		}

		//gets xyz coords from lat lon position and a given radius
		public static Vector3 getXYZCoords(Vector2 coords, float radius){
			Vector3 pos;
			//multiply my -1 because of the way the earth model is set up
			float lat = coords.x * -1;
			float lon = coords.y;
			
			float cosLat = Mathf.Cos(lat * Mathf.PI / 180);
			float sinLat = Mathf.Sin(lat * Mathf.PI / 180);
			float cosLon = Mathf.Cos(lon * Mathf.PI / 180);
			float sinLon = Mathf.Sin(lon * Mathf.PI / 180);
			
			pos.x = radius * cosLat * cosLon;
			pos.y = radius * cosLat * sinLon;
			pos.z = radius * sinLat;
			return pos;
		}
}


